# festivals-gateway configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
bind-host = "localhost"
port = 443
key = "TEST_SERVICE_KEY_001"

[tls]
festivaslapp-root-ca = "/usr/local/festivals-gateway/ca.crt"
cert = "/usr/local/festivals-gateway/server.crt"
key = "/usr/local/festivals-gateway/server.key"

[heartbeat]
endpoint = "localhost"
interval = 6

[authentication]
endpoint = "localhost"