# festivals-gateway configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-address = "localhost"
bind-host = "localhost"
port = 8080
key = "TEST_API_KEY_001"
website = "http://localhost:8080"

[tls]
festivaslapp-root-ca = "/usr/local/festivals-gateway/ca.crt"
cert = "//usr/local/festivals-gateway/server.crt"
key = "/usr/local/festivals-gateway/ca.key"

[heartbeat]
endpoint = "localhost"

[authentication]
api-keys = ["TEST_API_KEY_001", "TEST_API_KEY_002", "TEST_API_KEY_003"]
admin-keys = ["TEST_API_KEY_001"]